export const users = [
  {
    id: 1,
    name: "Arpit Chaudhary",
    email: "arpitchaudhary2003@gmail.com",
    role: "Admin",
    profileImage: "https://i.pravatar.cc/150?img=1",
  },
  {
    id: 2,
    name: "John Doe",
    email: "johndoe@example.com",
    role: "Volunteer",
    profileImage: "https://i.pravatar.cc/150?img=2",
  },
  {
    id: 3,
    name: "Jane Smith",
    email: "janesmith@example.com",
    role: "Team Lead",
    profileImage: "https://i.pravatar.cc/150?img=3",
  },
  {
    id: 4,
    name: "Alice Johnson",
    email: "alicejohnson@example.com",
    role: "Admin",
    profileImage: "https://i.pravatar.cc/150?img=4",
  },
  {
    id: 5,
    name: "Bob Williams",
    email: "bobwilliams@example.com",
    role: "Admin",
    profileImage: "https://i.pravatar.cc/150?img=5",
  },
];

export const oneToOneChats = [
  {
    id: 1,
    name: "John Doe",
    profileImage: "https://i.pravatar.cc/150?img=2",
    lastMessage: "Hey, when is the next volunteer meeting?",
    time: "10:30 AM",
    unreadCount: 2,
    online: true,
    messages: [
      {
        id: 101,
        senderId: 2,
        text: "Hey, when is the next volunteer meeting?",
        time: "10:30 AM",
        read: false,
      },
      {
        id: 100,
        senderId: 1,
        text: "We need to discuss the upcoming event",
        time: "10:25 AM",
        read: true,
      },
      {
        id: 99,
        senderId: 2,
        text: "Good morning Arpit!",
        time: "10:20 AM",
        read: true,
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    profileImage: "https://i.pravatar.cc/150?img=3",
    lastMessage: "The event was a great success!",
    time: "Yesterday",
    unreadCount: 0,
    online: false,
    messages: [
      {
        id: 98,
        senderId: 3,
        text: "The event was a great success!",
        time: "Yesterday",
        read: true,
      },
      {
        id: 97,
        senderId: 1,
        text: "How did the fundraising event go?",
        time: "Yesterday",
        read: true,
      },
      {
        id: 96,
        senderId: 3,
        text: "I'll send you the report by evening",
        time: "2 days ago",
        read: true,
      },
    ],
  },
  {
    id: 3,
    name: "Alice Johnson",
    profileImage: "https://i.pravatar.cc/150?img=4",
    lastMessage: "Please review the monthly report",
    time: "Yesterday",
    unreadCount: 1,
    online: true,
    messages: [
      {
        id: 95,
        senderId: 4,
        text: "Please review the monthly report",
        time: "Yesterday",
        read: false,
      },
      {
        id: 94,
        senderId: 4,
        text: "I've made all the changes you requested",
        time: "Yesterday",
        read: true,
      },
      {
        id: 93,
        senderId: 1,
        text: "Let me know when the report is ready",
        time: "2 days ago",
        read: true,
      },
    ],
  },
  {
    id: 4,
    name: "Bob Williams",
    profileImage: "https://i.pravatar.cc/150?img=5",
    lastMessage: "Thanks for your help today",
    time: "2 days ago",
    unreadCount: 0,
    online: false,
    messages: [
      {
        id: 92,
        senderId: 5,
        text: "Thanks for your help today",
        time: "2 days ago",
        read: true,
      },
      {
        id: 91,
        senderId: 1,
        text: "No problem, glad I could help",
        time: "2 days ago",
        read: true,
      },
      {
        id: 90,
        senderId: 5,
        text: "Can you assist with the donation sorting?",
        time: "2 days ago",
        read: true,
      },
    ],
  },
  {
    id: 5,
    name: "Emily Davis",
    profileImage: "https://i.pravatar.cc/150?img=6",
    lastMessage: "Can you help with the food drive on Saturday?",
    time: "11:45 AM",
    unreadCount: 3,
    online: true,
    messages: [
      {
        id: 89,
        senderId: 6,
        text: "Can you help with the food drive on Saturday?",
        time: "11:45 AM",
        read: false,
      },
      {
        id: 88,
        senderId: 6,
        text: "We need a few more volunteers",
        time: "11:44 AM",
        read: false,
      },
      {
        id: 87,
        senderId: 6,
        text: "The response has been great so far",
        time: "11:42 AM",
        read: false,
      },
    ],
  },
  {
    id: 6,
    name: "Michael Wilson",
    profileImage: "https://i.pravatar.cc/150?img=7",
    lastMessage: "I've updated the volunteer schedule",
    time: "Yesterday",
    unreadCount: 0,
    online: false,
    messages: [
      {
        id: 86,
        senderId: 7,
        text: "I've updated the volunteer schedule",
        time: "Yesterday",
        read: true,
      },
      {
        id: 85,
        senderId: 1,
        text: "Perfect, I'll take a look",
        time: "Yesterday",
        read: true,
      },
      {
        id: 84,
        senderId: 7,
        text: "We have a few gaps to fill for next week",
        time: "Yesterday",
        read: true,
      },
    ],
  },
  {
    id: 7,
    name: "Sarah Martinez",
    profileImage: "https://i.pravatar.cc/150?img=8",
    lastMessage: "Do you have the contact for the venue?",
    time: "2 days ago",
    unreadCount: 5,
    online: true,
    messages: [
      {
        id: 83,
        senderId: 8,
        text: "Do you have the contact for the venue?",
        time: "2 days ago",
        read: false,
      },
      {
        id: 82,
        senderId: 8,
        text: "The last email bounced back",
        time: "2 days ago",
        read: false,
      },
      {
        id: 81,
        senderId: 8,
        text: "We need to confirm the reservation",
        time: "2 days ago",
        read: false,
      },
    ],
  },
  {
    id: 8,
    name: "David Thompson",
    profileImage: "https://i.pravatar.cc/150?img=9",
    lastMessage: "The supplies are ready for pickup",
    time: "3 days ago",
    unreadCount: 0,
    online: false,
    messages: [
      {
        id: 80,
        senderId: 9,
        text: "The supplies are ready for pickup",
        time: "3 days ago",
        read: true,
      },
      {
        id: 79,
        senderId: 1,
        text: "Great, I'll send someone tomorrow",
        time: "3 days ago",
        read: true,
      },
      {
        id: 78,
        senderId: 9,
        text: "Everything is packed and labeled",
        time: "3 days ago",
        read: true,
      },
    ],
  },
  {
    id: 9,
    name: "Lisa Anderson",
    profileImage: "https://i.pravatar.cc/150?img=24",
    lastMessage: "I'll be late for tomorrow's meeting",
    time: "12:15 PM",
    unreadCount: 1,
    online: true,
    messages: [
      {
        id: 77,
        senderId: 10,
        text: "I'll be late for tomorrow's meeting",
        time: "12:15 PM",
        read: false,
      },
      {
        id: 76,
        senderId: 1,
        text: "What time can you make it?",
        time: "11:50 AM",
        read: true,
      },
      {
        id: 75,
        senderId: 10,
        text: "Can we discuss the upcoming project?",
        time: "11:45 AM",
        read: true,
      },
    ],
  },
  {
    id: 10,
    name: "Kevin Brown",
    profileImage: "https://i.pravatar.cc/150?img=25",
    lastMessage: "Did you receive my donation list?",
    time: "9:30 AM",
    unreadCount: 4,
    online: true,
    messages: [
      {
        id: 74,
        senderId: 11,
        text: "Did you receive my donation list?",
        time: "9:30 AM",
        read: false,
      },
      {
        id: 73,
        senderId: 11,
        text: "I sent it yesterday evening",
        time: "9:29 AM",
        read: false,
      },
      {
        id: 72,
        senderId: 11,
        text: "We have some great items this month",
        time: "9:28 AM",
        read: false,
      },
    ],
  },
  {
    id: 11,
    name: "Jennifer Taylor",
    profileImage: "https://i.pravatar.cc/150?img=26",
    lastMessage: "The new volunteer orientation is next week",
    time: "Yesterday",
    unreadCount: 0,
    online: false,
    messages: [
      {
        id: 71,
        senderId: 12,
        text: "The new volunteer orientation is next week",
        time: "Yesterday",
        read: true,
      },
      {
        id: 70,
        senderId: 1,
        text: "How many people have signed up?",
        time: "Yesterday",
        read: true,
      },
      {
        id: 69,
        senderId: 12,
        text: "About 15 so far, expecting more",
        time: "Yesterday",
        read: true,
      },
    ],
  },
  {
    id: 12,
    name: "Ryan Garcia",
    profileImage: "https://i.pravatar.cc/150?img=27",
    lastMessage: "Can you review the fundraising proposal?",
    time: "4 days ago",
    unreadCount: 2,
    online: false,
    messages: [
      {
        id: 68,
        senderId: 13,
        text: "Can you review the fundraising proposal?",
        time: "4 days ago",
        read: false,
      },
      {
        id: 67,
        senderId: 13,
        text: "I've added the budget section",
        time: "4 days ago",
        read: false,
      },
      {
        id: 66,
        senderId: 1,
        text: "I'll try to get to it tomorrow",
        time: "5 days ago",
        read: true,
      },
    ],
  },
  {
    id: 13,
    name: "Michelle Lee",
    profileImage: "https://i.pravatar.cc/150?img=28",
    lastMessage: "Thanks for organizing the community event!",
    time: "1:20 PM",
    unreadCount: 0,
    online: true,
    messages: [
      {
        id: 65,
        senderId: 14,
        text: "Thanks for organizing the community event!",
        time: "1:20 PM",
        read: true,
      },
      {
        id: 64,
        senderId: 1,
        text: "It was a team effort, glad it went well",
        time: "1:15 PM",
        read: true,
      },
      {
        id: 63,
        senderId: 14,
        text: "Everyone loved the activities",
        time: "1:10 PM",
        read: true,
      },
    ],
  },
  {
    id: 14,
    name: "Daniel Clark",
    profileImage: "https://i.pravatar.cc/150?img=29",
    lastMessage: "I've sent you the updated budget sheet",
    time: "Yesterday",
    unreadCount: 1,
    online: false,
    messages: [
      {
        id: 62,
        senderId: 15,
        text: "I've sent you the updated budget sheet",
        time: "Yesterday",
        read: false,
      },
      {
        id: 61,
        senderId: 1,
        text: "Thanks, I'll check it later today",
        time: "Yesterday",
        read: true,
      },
      {
        id: 60,
        senderId: 15,
        text: "We're under budget for this quarter",
        time: "Yesterday",
        read: true,
      },
    ],
  },
];

export const groupChats = [
  {
    id: 1,
    name: "Event Planning Team",
    profileImage: "https://i.pravatar.cc/150?img=10",
    lastMessage: "Let's finalize the venue by tomorrow",
    time: "11:45 AM",
    unreadCount: 5,
    participants: 8,
    groupAdmin: "Arpit Chaudhary",
    members: [1, 2, 3, 4, 5, 9, 10, 12],
    description:
      "Team responsible for planning and organizing community events",
    memberImages: [
      "https://i.pravatar.cc/150?img=1",
      "https://i.pravatar.cc/150?img=2",
      "https://i.pravatar.cc/150?img=3",
    ],
    messages: [
      {
        id: 201,
        senderId: 3,
        senderName: "Jane Smith",
        senderImage: "https://i.pravatar.cc/150?img=3",
        text: "Let's finalize the venue by tomorrow",
        time: "11:45 AM",
      },
      {
        id: 202,
        senderId: 1,
        senderName: "Arpit Chaudhary",
        senderImage: "https://i.pravatar.cc/150?img=1",
        text: "I agree, we need to move forward with the planning",
        time: "11:30 AM",
      },
      {
        id: 203,
        senderId: 2,
        senderName: "John Doe",
        senderImage: "https://i.pravatar.cc/150?img=2",
        text: "I've contacted three potential venues so far",
        time: "11:15 AM",
      },
    ],
  },
  {
    id: 2,
    name: "Volunteer Coordination",
    profileImage: "https://i.pravatar.cc/150?img=11",
    lastMessage: "Updated schedule for next week",
    time: "Yesterday",
    unreadCount: 3,
    participants: 15,
    groupAdmin: "Jane Smith",
    members: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
    description: "Coordination of volunteer schedules and activities",
    memberImages: [
      "https://i.pravatar.cc/150?img=3",
      "https://i.pravatar.cc/150?img=4",
      "https://i.pravatar.cc/150?img=5",
    ],
    messages: [
      {
        id: 204,
        senderId: 3,
        senderName: "Jane Smith",
        senderImage: "https://i.pravatar.cc/150?img=3",
        text: "Updated schedule for next week",
        time: "Yesterday",
      },
      {
        id: 205,
        senderId: 4,
        senderName: "Alice Johnson",
        senderImage: "https://i.pravatar.cc/150?img=4",
        text: "I can cover the morning shift on Thursday",
        time: "Yesterday",
      },
      {
        id: 206,
        senderId: 5,
        senderName: "Bob Williams",
        senderImage: "https://i.pravatar.cc/150?img=5",
        text: "I'll be out of town on Friday, need someone to cover",
        time: "2 days ago",
      },
    ],
  },
  {
    id: 3,
    name: "Admin Announcements",
    profileImage: "https://i.pravatar.cc/150?img=12",
    lastMessage: "Important: New guidelines for events",
    time: "2 days ago",
    unreadCount: 1,
    participants: 5,
    groupAdmin: "Arpit Chaudhary",
    members: [1, 4, 5],
    description: "Official announcements from administration",
    memberImages: [
      "https://i.pravatar.cc/150?img=1",
      "https://i.pravatar.cc/150?img=4",
      "https://i.pravatar.cc/150?img=5",
    ],
    messages: [
      {
        id: 207,
        senderId: 1,
        senderName: "Arpit Chaudhary",
        senderImage: "https://i.pravatar.cc/150?img=1",
        text: "Important: New guidelines for events",
        time: "2 days ago",
      },
      {
        id: 208,
        senderId: 4,
        senderName: "Alice Johnson",
        senderImage: "https://i.pravatar.cc/150?img=4",
        text: "Thanks for the update. Will implement immediately.",
        time: "2 days ago",
      },
      {
        id: 209,
        senderId: 1,
        senderName: "Arpit Chaudhary",
        senderImage: "https://i.pravatar.cc/150?img=1",
        text: "Please review the attached document for all details",
        time: "2 days ago",
      },
    ],
  },
  {
    id: 4,
    name: "Team Leaders",
    profileImage: "https://i.pravatar.cc/150?img=13",
    lastMessage: "Monthly progress report due next week",
    time: "3 days ago",
    unreadCount: 0,
    participants: 6,
    groupAdmin: "Alice Johnson",
    members: [1, 3, 4, 5, 6, 11],
    description: "Coordination between team leaders across departments",
    memberImages: [
      "https://i.pravatar.cc/150?img=4",
      "https://i.pravatar.cc/150?img=3",
      "https://i.pravatar.cc/150?img=7",
    ],
    messages: [
      {
        id: 210,
        senderId: 4,
        senderName: "Alice Johnson",
        senderImage: "https://i.pravatar.cc/150?img=4",
        text: "Monthly progress report due next week",
        time: "3 days ago",
      },
      {
        id: 211,
        senderId: 3,
        senderName: "Jane Smith",
        senderImage: "https://i.pravatar.cc/150?img=3",
        text: "I'll have my team's data ready by Friday",
        time: "3 days ago",
      },
      {
        id: 212,
        senderId: 6,
        senderName: "Michael Wilson",
        senderImage: "https://i.pravatar.cc/150?img=7",
        text: "Any specific metrics we should focus on this month?",
        time: "3 days ago",
      },
    ],
  },
  {
    id: 5,
    name: "Community Outreach",
    profileImage: "https://i.pravatar.cc/150?img=14",
    lastMessage: "New partnership with local business confirmed",
    time: "12:15 PM",
    unreadCount: 7,
    participants: 12,
    groupAdmin: "Bob Williams",
    members: [1, 2, 3, 5, 6, 7, 8, 9, 10, 12, 13, 14],
    description: "Planning and executing community outreach initiatives",
    memberImages: [
      "https://i.pravatar.cc/150?img=5",
      "https://i.pravatar.cc/150?img=2",
      "https://i.pravatar.cc/150?img=9",
    ],
    messages: [
      {
        id: 213,
        senderId: 5,
        senderName: "Bob Williams",
        senderImage: "https://i.pravatar.cc/150?img=5",
        text: "New partnership with local business confirmed",
        time: "12:15 PM",
      },
      {
        id: 214,
        senderId: 2,
        senderName: "John Doe",
        senderImage: "https://i.pravatar.cc/150?img=2",
        text: "That's fantastic news! What are the details?",
        time: "12:10 PM",
      },
      {
        id: 215,
        senderId: 9,
        senderName: "Lisa Anderson",
        senderImage: "https://i.pravatar.cc/150?img=24",
        text: "Will they be sponsoring the summer event?",
        time: "12:05 PM",
      },
    ],
  },
  {
    id: 6,
    name: "Fundraising Committee",
    profileImage: "https://i.pravatar.cc/150?img=15",
    lastMessage: "We reached 80% of our goal!",
    time: "Yesterday",
    unreadCount: 2,
    participants: 9,
    groupAdmin: "Arpit Chaudhary",
    members: [1, 2, 3, 8, 9, 10, 11, 12, 14],
    description: "Planning and coordinating fundraising activities",
    memberImages: [
      "https://i.pravatar.cc/150?img=1",
      "https://i.pravatar.cc/150?img=9",
      "https://i.pravatar.cc/150?img=10",
    ],
    messages: [
      {
        id: 216,
        senderId: 1,
        senderName: "Arpit Chaudhary",
        senderImage: "https://i.pravatar.cc/150?img=1",
        text: "We reached 80% of our goal!",
        time: "Yesterday",
      },
      {
        id: 217,
        senderId: 9,
        senderName: "Lisa Anderson",
        senderImage: "https://i.pravatar.cc/150?img=24",
        text: "Amazing progress! Let's push for the last 20%",
        time: "Yesterday",
      },
      {
        id: 218,
        senderId: 10,
        senderName: "Kevin Brown",
        senderImage: "https://i.pravatar.cc/150?img=25",
        text: "I have a few more corporate sponsors to approach",
        time: "Yesterday",
      },
    ],
  },
  {
    id: 7,
    name: "Tech Support",
    profileImage: "https://i.pravatar.cc/150?img=16",
    lastMessage: "Website update scheduled for next Monday",
    time: "2 days ago",
    unreadCount: 1,
    participants: 7,
    groupAdmin: "John Doe",
    members: [1, 2, 4, 5, 7, 12, 14],
    description: "Technical support and website management",
    memberImages: [
      "https://i.pravatar.cc/150?img=2",
      "https://i.pravatar.cc/150?img=5",
      "https://i.pravatar.cc/150?img=12",
    ],
    messages: [
      {
        id: 219,
        senderId: 2,
        senderName: "John Doe",
        senderImage: "https://i.pravatar.cc/150?img=2",
        text: "Website update scheduled for next Monday",
        time: "2 days ago",
      },
      {
        id: 220,
        senderId: 5,
        senderName: "Bob Williams",
        senderImage: "https://i.pravatar.cc/150?img=5",
        text: "Any expected downtime during the update?",
        time: "2 days ago",
      },
      {
        id: 221,
        senderId: 12,
        senderName: "Ryan Garcia",
        senderImage: "https://i.pravatar.cc/150?img=27",
        text: "I can help test the new features after deployment",
        time: "2 days ago",
      },
    ],
  },
  {
    id: 8,
    name: "New Volunteer Onboarding",
    profileImage: "https://i.pravatar.cc/150?img=17",
    lastMessage: "Welcome to the team! Training materials attached",
    time: "1:30 PM",
    unreadCount: 9,
    participants: 22,
    groupAdmin: "Jane Smith",
    members: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
    description: "Welcoming and training new volunteers",
    memberImages: [
      "https://i.pravatar.cc/150?img=3",
      "https://i.pravatar.cc/150?img=8",
      "https://i.pravatar.cc/150?img=14",
    ],
    messages: [
      {
        id: 222,
        senderId: 3,
        senderName: "Jane Smith",
        senderImage: "https://i.pravatar.cc/150?img=3",
        text: "Welcome to the team! Training materials attached",
        time: "1:30 PM",
      },
      {
        id: 223,
        senderId: 8,
        senderName: "David Thompson",
        senderImage: "https://i.pravatar.cc/150?img=9",
        text: "Thanks for the warm welcome!",
        time: "1:25 PM",
      },
      {
        id: 224,
        senderId: 14,
        senderName: "Daniel Clark",
        senderImage: "https://i.pravatar.cc/150?img=29",
        text: "Looking forward to working with everyone",
        time: "1:20 PM",
      },
    ],
  },
  {
    id: 9,
    name: "Crisis Response Team",
    profileImage: "https://i.pravatar.cc/150?img=18",
    lastMessage: "Emergency protocols updated - please review",
    time: "10:45 AM",
    unreadCount: 4,
    participants: 11,
    groupAdmin: "Alice Johnson",
    members: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    description: "Coordination for emergency and crisis situations",
    memberImages: [
      "https://i.pravatar.cc/150?img=4",
      "https://i.pravatar.cc/150?img=6",
      "https://i.pravatar.cc/150?img=11",
    ],
    messages: [
      {
        id: 225,
        senderId: 4,
        senderName: "Alice Johnson",
        senderImage: "https://i.pravatar.cc/150?img=4",
        text: "Emergency protocols updated - please review",
        time: "10:45 AM",
      },
      {
        id: 226,
        senderId: 6,
        senderName: "Michael Wilson",
        senderImage: "https://i.pravatar.cc/150?img=7",
        text: "Reviewing now, will provide feedback shortly",
        time: "10:40 AM",
      },
      {
        id: 227,
        senderId: 11,
        senderName: "Jennifer Taylor",
        senderImage: "https://i.pravatar.cc/150?img=26",
        text: "Should we schedule a drill to test the new protocols?",
        time: "10:35 AM",
      },
    ],
  },
  {
    id: 10,
    name: "Social Media Coordinators",
    profileImage: "https://i.pravatar.cc/150?img=19",
    lastMessage: "Content calendar for next month is ready",
    time: "Yesterday",
    unreadCount: 0,
    participants: 8,
    groupAdmin: "Bob Williams",
    members: [1, 2, 5, 7, 9, 11, 12, 14],
    description: "Managing our social media presence and content",
    memberImages: [
      "https://i.pravatar.cc/150?img=5",
      "https://i.pravatar.cc/150?img=7",
      "https://i.pravatar.cc/150?img=24",
    ],
    messages: [
      {
        id: 228,
        senderId: 5,
        senderName: "Bob Williams",
        senderImage: "https://i.pravatar.cc/150?img=5",
        text: "Content calendar for next month is ready",
        time: "Yesterday",
      },
      {
        id: 229,
        senderId: 7,
        senderName: "Sarah Martinez",
        senderImage: "https://i.pravatar.cc/150?img=8",
        text: "Great! I'll start preparing the graphics",
        time: "Yesterday",
      },
      {
        id: 230,
        senderId: 9,
        senderName: "Lisa Anderson",
        senderImage: "https://i.pravatar.cc/150?img=24",
        text: "Can we highlight the fundraising success in the next post?",
        time: "Yesterday",
      },
    ],
  },
  {
    id: 11,
    name: "Youth Program Leaders",
    profileImage: "https://i.pravatar.cc/150?img=20",
    lastMessage: "Summer camp registration opens next week",
    time: "3 days ago",
    unreadCount: 6,
    participants: 14,
    groupAdmin: "Arpit Chaudhary",
    members: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
    description: "Coordinating youth-focused volunteer activities and programs",
    memberImages: [
      "https://i.pravatar.cc/150?img=1",
      "https://i.pravatar.cc/150?img=13",
      "https://i.pravatar.cc/150?img=27",
    ],
    messages: [
      {
        id: 231,
        senderId: 1,
        senderName: "Arpit Chaudhary",
        senderImage: "https://i.pravatar.cc/150?img=1",
        text: "Summer camp registration opens next week",
        time: "3 days ago",
      },
      {
        id: 232,
        senderId: 12,
        senderName: "Ryan Garcia",
        senderImage: "https://i.pravatar.cc/150?img=27",
        text: "How many spots are available this year?",
        time: "3 days ago",
      },
      {
        id: 233,
        senderId: 13,
        senderName: "Michelle Lee",
        senderImage: "https://i.pravatar.cc/150?img=28",
        text: "I've finalized the activities schedule",
        time: "3 days ago",
      },
    ],
  },
  {
    id: 12,
    name: "Transportation Logistics",
    profileImage: "https://i.pravatar.cc/150?img=21",
    lastMessage: "Need 3 more drivers for Friday's event",
    time: "4:20 PM",
    unreadCount: 2,
    participants: 10,
    groupAdmin: "John Doe",
    members: [1, 2, 3, 5, 6, 8, 10, 12, 13, 14],
    description: "Planning and coordinating transportation for events",
    memberImages: [
      "https://i.pravatar.cc/150?img=2",
      "https://i.pravatar.cc/150?img=8",
      "https://i.pravatar.cc/150?img=25",
    ],
    messages: [
      {
        id: 234,
        senderId: 2,
        senderName: "John Doe",
        senderImage: "https://i.pravatar.cc/150?img=2",
        text: "Need 3 more drivers for Friday's event",
        time: "4:20 PM",
      },
      {
        id: 235,
        senderId: 8,
        senderName: "David Thompson",
        senderImage: "https://i.pravatar.cc/150?img=9",
        text: "I can drive my van, it fits 8 people",
        time: "4:15 PM",
      },
      {
        id: 236,
        senderId: 10,
        senderName: "Kevin Brown",
        senderImage: "https://i.pravatar.cc/150?img=25",
        text: "What time do we need to arrive?",
        time: "4:10 PM",
      },
    ],
  },
  {
    id: 13,
    name: "Food Distribution Team",
    profileImage: "https://i.pravatar.cc/150?img=22",
    lastMessage: "Updated inventory list attached",
    time: "Yesterday",
    unreadCount: 1,
    participants: 18,
    groupAdmin: "Jane Smith",
    members: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
    description: "Organizing food collection and distribution to those in need",
    memberImages: [
      "https://i.pravatar.cc/150?img=3",
      "https://i.pravatar.cc/150?img=28",
      "https://i.pravatar.cc/150?img=12",
    ],
    messages: [
      {
        id: 237,
        senderId: 3,
        senderName: "Jane Smith",
        senderImage: "https://i.pravatar.cc/150?img=3",
        text: "Updated inventory list attached",
        time: "Yesterday",
      },
      {
        id: 238,
        senderId: 13,
        senderName: "Michelle Lee",
        senderImage: "https://i.pravatar.cc/150?img=28",
        text: "We're running low on canned vegetables",
        time: "Yesterday",
      },
      {
        id: 239,
        senderId: 12,
        senderName: "Ryan Garcia",
        senderImage: "https://i.pravatar.cc/150?img=27",
        text: "I'll contact our grocery store partners for donations",
        time: "Yesterday",
      },
    ],
  },
  {
    id: 14,
    name: "Senior Support Network",
    profileImage: "https://i.pravatar.cc/150?img=23",
    lastMessage: "New assistance requests - please sign up",
    time: "4 days ago",
    unreadCount: 0,
    participants: 16,
    groupAdmin: "Alice Johnson",
    members: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
    description: "Coordinating support services for senior citizens",
    memberImages: [
      "https://i.pravatar.cc/150?img=4",
      "https://i.pravatar.cc/150?img=29",
      "https://i.pravatar.cc/150?img=6",
    ],
    messages: [
      {
        id: 240,
        senderId: 4,
        senderName: "Alice Johnson",
        senderImage: "https://i.pravatar.cc/150?img=4",
        text: "New assistance requests - please sign up",
        time: "4 days ago",
      },
      {
        id: 241,
        senderId: 14,
        senderName: "Daniel Clark",
        senderImage: "https://i.pravatar.cc/150?img=29",
        text: "I can take the medication delivery route this week",
        time: "4 days ago",
      },
      {
        id: 242,
        senderId: 6,
        senderName: "Michael Wilson",
        senderImage: "https://i.pravatar.cc/150?img=7",
        text: "Is anyone available to help with grocery shopping on Thursday?",
        time: "4 days ago",
      },
    ],
  },
];
